//! Media tracking modes and the media catalog.
//!
//! The catalog (`data/media_catalog.json`, generated by
//! `scripts/generate_media_catalog.py` from Print Master's bundled media
//! definitions) groups media presets into paper pools and maps printer
//! types onto them. It is compiled into the crate.
//!
//! All name lookups ignore ASCII case and surrounding whitespace.

use std::sync::LazyLock;

use serde::Deserialize;

/// How the printer finds the start of the next label.
///
/// These are Print Master's paper types 0, 2, 3 and 4 (`QuinPrinter.setPaperType`,
/// `re/protocol/commands.md`, "Paper Type / Tracking"), sent with
/// [`Command::SetMediaTracking`](crate::commands::Command::SetMediaTracking).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MediaTracking {
    /// Continuous roll: no label detection.
    Continuous,
    /// Labels separated by gaps.
    Gap,
    /// Labels marked by a black line on the back.
    Mark,
    /// Card stock. Print Master's card templates select [`Mark`](Self::Mark)
    /// and then this.
    Card,
}

/// One media size.
#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct MediaPreset {
    /// PWG self-describing size name, e.g. `om_40x30mm_40x30mm`.
    pub size_name: String,
    /// Width across the print head, in millimetres.
    pub width_mm: f32,
    /// Length along the feed, in millimetres; 0 for a continuous roll.
    pub length_mm: f32,
    /// The tracking mode to use for this size.
    pub tracking_default: MediaTracking,
    /// Every tracking mode this size comes in.
    #[serde(default)]
    pub tracking_supported: Vec<MediaTracking>,
}

impl MediaPreset {
    /// Width in hundredths of a millimetre, rounded.
    #[must_use]
    pub fn width_hundredths_mm(&self) -> i32 {
        hundredths(self.width_mm)
    }

    /// Length in hundredths of a millimetre, rounded.
    #[must_use]
    pub fn length_hundredths_mm(&self) -> i32 {
        hundredths(self.length_mm)
    }
}

#[expect(
    clippy::cast_possible_truncation,
    reason = "media dimensions are far below i32::MAX hundredths of a millimetre"
)]
fn hundredths(mm: f32) -> i32 {
    (mm * 100.0).round() as i32
}

/// The media shared by a group of printers.
#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct PaperPool {
    /// Pool name, e.g. `M200`.
    #[serde(rename = "pool")]
    pub name: String,
    /// [`size_name`](MediaPreset::size_name) of the default preset.
    pub default_size_name: String,
    /// The presets, by width then length.
    pub media: Vec<MediaPreset>,
}

impl PaperPool {
    /// The preset named `size_name`.
    #[must_use]
    pub fn find(&self, size_name: &str) -> Option<&MediaPreset> {
        self.media
            .iter()
            .find(|preset| names_match(&preset.size_name, size_name))
    }

    /// The default preset.
    #[must_use]
    pub fn default_media(&self) -> Option<&MediaPreset> {
        self.find(&self.default_size_name)
    }
}

/// The paper pool for a printer type (e.g. `M220`) or a pool name (e.g.
/// `M200`).
#[must_use]
pub fn paper_pool(printer_type_or_pool: &str) -> Option<&'static PaperPool> {
    let catalog = &*CATALOG;
    let pool = catalog
        .printer_types
        .iter()
        .find(|printer| names_match(&printer.name, printer_type_or_pool))
        .map_or(printer_type_or_pool, |printer| printer.pool.as_str());
    catalog
        .paper_pools
        .iter()
        .find(|candidate| names_match(&candidate.name, pool))
}

fn names_match(a: &str, b: &str) -> bool {
    a.trim().eq_ignore_ascii_case(b.trim())
}

#[derive(Debug, Deserialize)]
struct Catalog {
    paper_pools: Vec<PaperPool>,
    printer_types: Vec<PrinterType>,
}

#[derive(Debug, Deserialize)]
struct PrinterType {
    #[serde(rename = "type")]
    name: String,
    pool: String,
}

/// The embedded catalog. It is compiled in and checked by the tests below,
/// so failing to parse it is a build defect, not a runtime condition.
static CATALOG: LazyLock<Catalog> = LazyLock::new(|| {
    serde_json::from_str(include_str!("../data/media_catalog.json"))
        .unwrap_or_else(|err| panic!("embedded media catalog is invalid: {err}"))
});

#[cfg(test)]
mod tests {
    use super::*;

    fn pool(name: &str) -> &'static PaperPool {
        paper_pool(name).unwrap_or_else(|| panic!("no paper pool for {name}"))
    }

    #[test]
    fn catalog_is_consistent() {
        let catalog = &*CATALOG;
        assert!(!catalog.paper_pools.is_empty());
        for pool in &catalog.paper_pools {
            assert!(!pool.media.is_empty(), "{} has no media", pool.name);
            assert!(
                pool.default_media().is_some(),
                "{}: default {} missing",
                pool.name,
                pool.default_size_name
            );
            for preset in &pool.media {
                assert!(
                    preset.tracking_supported.contains(&preset.tracking_default),
                    "{}: {} defaults to an unsupported tracking mode",
                    pool.name,
                    preset.size_name
                );
            }
        }
        for printer in &catalog.printer_types {
            assert!(
                paper_pool(&printer.pool).is_some(),
                "{} maps to missing pool {}",
                printer.name,
                printer.pool
            );
        }
    }

    #[test]
    fn printer_types_resolve_to_their_pool() {
        assert_eq!(pool("M220").name, "M200");
        assert_eq!(pool("M110").name, "M110");
        assert_eq!(pool("D35").name, "D30");
    }

    #[test]
    fn pool_names_resolve_directly() {
        assert_eq!(pool("P3100").name, "P3100");
    }

    #[test]
    fn lookups_ignore_case_and_whitespace() {
        assert_eq!(pool(" m220 "), pool("M220"));
        let pool = pool("M220");
        assert_eq!(
            pool.find("OM_40X30MM_40X30MM"),
            pool.find("om_40x30mm_40x30mm")
        );
    }

    #[test]
    fn unknown_names_have_no_pool() {
        assert_eq!(paper_pool("not-a-printer"), None);
        assert_eq!(pool("M220").find("om_999x999mm_999x999mm"), None);
    }

    #[test]
    fn m200_default_is_a_40x30_gap_label() {
        let default = pool("M220").default_media().expect("catalog is consistent");
        assert_eq!(default.size_name, "om_40x30mm_40x30mm");
        assert_eq!(default.tracking_default, MediaTracking::Gap);
        assert_eq!(
            (
                default.width_hundredths_mm(),
                default.length_hundredths_mm()
            ),
            (4000, 3000)
        );
    }

    #[test]
    fn coerced_paper_types_are_present() {
        // localPaper.json spells some M110 paper types as ":2"; the
        // generator coerces them rather than dropping the entries.
        let preset = pool("M110")
            .find("om_20x20mm_20x20mm")
            .expect("20x20 label");
        assert_eq!(preset.tracking_default, MediaTracking::Gap);
    }

    #[test]
    fn continuous_rolls_are_synthesized() {
        let roll = pool("M220").find("om_40x0mm_40x0mm").expect("40 mm roll");
        assert_eq!(roll.length_hundredths_mm(), 0);
        assert_eq!(roll.tracking_supported, [MediaTracking::Continuous]);
    }
}
